export enum DefaultThemeColors {
    white = 'white',
    black = 'black',
    black06 = 'black-06',
    green1 = 'green-1',
    green2 = 'green-2',
    green3 = 'green-3',
    green4 = 'green-4',
    grey1 = 'grey-1',
    grey2 = 'grey-2',
    grey3 = 'grey-3',
    grey4 = 'grey-4',
    grey5 = 'grey-5',
    greyBG = 'grey-bg',
    red1 = 'red-1',
    yellow1 = 'yellow-1',
    greenGradient1 = 'green-gradient-1',
    greenGradient2 = 'green-gradient-2',
    greenGradient3 = 'green-gradient-3',
    greyGradient1 = 'grey-gradient-1',
    buttonBackColor = '#002766',
    signInBackColor = '#ECECEC',
    eyeOutLined = '#b8cfff',
}
